# SPDX-FileCopyrightText: (C) 2025 chris montgomery <chmont@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[global]
excludes = ["**/node_modules/**", "**/vendor/**", "**/*.min.*"]

[formatter.biome]
command = "biome"
options = [
  "check",
  "--write",
  "--no-errors-on-unmatched",
  "--files-ignore-unknown=true",
]
includes = [
  "*.css",
  "*.js",
  "*.ts",
  "*.mjs",
  "*.mts",
  "*.cjs",
  "*.cts",
  "*.jsx",
  "*.tsx",
  "*.d.ts",
  "*.d.cts",
  "*.d.mts",
  "*.json",
  "*.jsonc",
]
excludes = []

[formatter.nixfmt]
command = "nixfmt"
options = []
includes = ["*.nix"]
excludes = []

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
excludes = []
